version: "3.6"
services:
  login:
    container_name: "rA_login"
    image: rathena
    build: .
    ports:
      - 6900:6900
    volumes:
      - ./conf/:/opt/rathena/custom-conf
    command: login
    init: true # helps with signal forwarding and process reaping
    tty: true
    stdin_open: true
  char:
    container_name: "rA_char"
    image: rathena
    ports:
      - 6121:6121
    volumes:
      - ./conf/:/opt/rathena/custom-conf
    command: char
    init: true # helps with signal forwarding and process reaping
    tty: true
    stdin_open: true
    depends_on:
      - login
  map:
    container_name: "rA_map"
    image: rathena
    ports:
      - 5121:5121
    volumes:
      - ./conf/:/opt/rathena/custom-conf
      - ./npc/:/opt/rathena/custom-npc
      - ./mapcache/map_cache.dat:/opt/rathena/db/import/map_cache.dat
    command: map
    init: true # helps with signal forwarding and process reaping
    tty: true
    stdin_open: true
    depends_on:
      - char
